# Generated by Django 4.2.4 on 2023-08-29 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('news_title', models.CharField(max_length=50)),
                ('news_description', models.TextField()),
                ('news_image', models.ImageField(upload_to='', verbose_name='media/news')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
