# Generated by Django 4.2.4 on 2023-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='media/news'),
        ),
    ]
