# Generated by Django 4.2.4 on 2023-09-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_is_publish', 'Can is Publish')], 'verbose_name_plural': 'News'},
        ),
    ]
