# Generated by Django 4.2.4 on 2023-08-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_is_published_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='published_date',
            new_name='created_at',
        ),
    ]
