# Generated by Django 4.2.4 on 2023-08-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_published_date_publish_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='created_at',
        ),
    ]
