# Generated by Django 4.2.4 on 2023-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_publish_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
