# Generated by Django 4.2.4 on 2023-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, default='media/news/Logo_PLN.png', null=True, upload_to='media/news'),
        ),
    ]
