# Generated by Django 4.2.4 on 2023-08-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_published',
            new_name='is_publish',
        ),
    ]
