# Generated by Django 4.2.4 on 2023-08-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_created_at_gallery_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
