# Generated by Django 4.2.4 on 2023-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery_image',
            field=models.ImageField(upload_to='media/gallery'),
        ),
    ]
