# Generated by Django 4.2.4 on 2023-08-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='galery_name',
            new_name='gallery_name',
        ),
    ]
