# Generated by Django 4.2.4 on 2023-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.PositiveIntegerField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('maps', models.TextField(blank=True, default='<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13403.817845341626!2d114.20907390581237!3d-2.822293743327662!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2de4809c26c1fa4d%3A0x19afdeccec4715ea!2sPT.%20PLN%20Nusantara%20Power%20Pulang%20Pisau%202x60MW!5e0!3m2!1sid!2sid!4v1693568653094!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
