# Generated by Django 4.2.4 on 2023-08-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuservices',
            old_name='description_menu',
            new_name='menu_description',
        ),
        migrations.RenameField(
            model_name='menuservices',
            old_name='icon',
            new_name='menu_icon',
        ),
        migrations.RenameField(
            model_name='menuservices',
            old_name='title_menu',
            new_name='menu_title',
        ),
    ]
