# Generated by Django 4.2.4 on 2023-08-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_description_menu_menuservices_menu_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuservices',
            options={'verbose_name_plural': 'Menu Services'},
        ),
    ]
