# Generated by Django 4.2.4 on 2023-08-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='background_image',
            field=models.ImageField(upload_to='media/bgintro'),
        ),
    ]
