# Generated by Django 4.2.4 on 2023-08-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0004_alter_intro_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('escription', models.TextField(max_length=655)),
                ('image', models.ImageField(upload_to='media/bgintro')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
