# Generated by Django 4.2.4 on 2023-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
