# Generated by Django 4.2.4 on 2023-08-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0006_aboutus_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='escription',
            new_name='description',
        ),
    ]
