# Generated by Django 4.2.4 on 2023-08-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0009_menuservices_alter_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuservices',
            options={'verbose_name_plural': 'MenuServices'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='menuservices',
            name='icon',
            field=models.CharField(max_length=40),
        ),
    ]
