# Generated by Django 4.2.4 on 2023-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0012_alter_menuservices_description_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
