# Generated by Django 4.2.4 on 2023-08-27 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0015_backgroundimage_remove_intro_background_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundImage',
            new_name='BackgroundImageIntro',
        ),
        migrations.AlterModelOptions(
            name='backgroundimageintro',
            options={'verbose_name_plural': 'Background Image Intro'},
        ),
    ]
