# Generated by Django 4.2.4 on 2023-08-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0016_rename_backgroundimage_backgroundimageintro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimageintro',
            name='image_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
