# Generated by Django 4.2.4 on 2023-08-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0017_backgroundimageintro_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
