# Generated by Django 4.2.4 on 2023-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0019_about_misi_about_visi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuservices',
            name='description_menu',
            field=models.TextField(),
        ),
    ]
