# Generated by Django 4.2.4 on 2023-08-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0020_alter_menuservices_description_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuservices',
            name='title_menu',
            field=models.CharField(max_length=50),
        ),
    ]
