# Generated by Django 4.2.4 on 2023-08-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0023_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='menu_services',
        ),
        migrations.DeleteModel(
            name='MenuServices',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
