# Generated by Django 4.2.4 on 2023-09-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plnnusantarapower', '0024_remove_services_menu_services_delete_menuservices_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
