# Generated by Django 4.2.4 on 2023-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lihatberita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lihatberita',
            options={'verbose_name_plural': 'Lihat Berita'},
        ),
        migrations.RenameField(
            model_name='lihatberita',
            old_name='lihat_berita_button_name',
            new_name='button_name',
        ),
        migrations.RenameField(
            model_name='lihatberita',
            old_name='lihat_berita_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lihatberita',
            old_name='lihat_berita_title',
            new_name='title',
        ),
    ]
