# Generated by Django 4.2.4 on 2023-08-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=655)),
                ('is_published', models.BooleanField(default=False)),
                ('background_image', models.ImageField(upload_to='media/backgroundintro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
