# Generated by Django 4.2.4 on 2023-08-17 17:35

import intro.validatiors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0007_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='background_image',
            field=models.ImageField(upload_to='media/bgintro'),
        ),
    ]
