# Generated by Django 4.2.4 on 2023-08-21 10:43

import companyprofile.validatiors
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0008_alter_intro_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_menu', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=10)),
                ('description_menu', models.CharField(max_length=130)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='media/aboutus'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='background_image',
            field=models.ImageField(upload_to='media/bgintro', validators=[companyprofile.validatiors.validate_aspect_ratio_1920_900]),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyprofile.menuservices')),
            ],
        ),
    ]
