# Generated by Django 4.2.4 on 2023-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0010_alter_menuservices_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='menu_services',
        ),
        migrations.AddField(
            model_name='services',
            name='menu_services',
            field=models.ManyToManyField(to='companyprofile.menuservices'),
        ),
    ]
