# Generated by Django 4.2.4 on 2023-08-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0011_remove_services_menu_services_services_menu_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuservices',
            name='description_menu',
            field=models.TextField(max_length=140),
        ),
    ]
