# Generated by Django 4.2.4 on 2023-08-27 02:23

import intro.validatiors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0014_email_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/bgintro', validators=[intro.validatiors.validate_aspect_ratio_1920_900])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Background Image',
            },
        ),
        migrations.RemoveField(
            model_name='intro',
            name='background_image',
        ),
        migrations.AddField(
            model_name='intro',
            name='background_image',
            field=models.ManyToManyField(to='companyprofile.backgroundimage'),
        ),
    ]
