# Generated by Django 4.2.4 on 2023-08-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0018_rename_aboutus_about_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='misi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='visi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
