# Generated by Django 4.2.4 on 2023-08-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0022_remove_intro_background_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
