# Generated by Django 4.2.4 on 2023-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('author', 'Author'), ('publisher', 'Publisher')], default='none', max_length=10),
        ),
    ]
