# Generated by Django 4.2.4 on 2023-09-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
