# Generated by Django 4.2.4 on 2023-08-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
