# Generated by Django 4.2.4 on 2023-09-03 02:13

from django.db import migrations, models
import intro.validatiors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_name', models.CharField(max_length=30)),
                ('bg_image', models.ImageField(upload_to='media/intro', validators=[intro.validatiors.validate_aspect_ratio_1920_900])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Background Image Intro',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=655)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ManyToManyField(blank=True, to='intro.backgroundimageintro')),
            ],
            options={
                'verbose_name_plural': 'Intro',
            },
        ),
    ]
