# Generated by Django 4.2.4 on 2023-08-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimageintro',
            old_name='image',
            new_name='bg_image',
        ),
        migrations.RenameField(
            model_name='backgroundimageintro',
            old_name='image_name',
            new_name='bg_name',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='background_image',
            new_name='image',
        ),
    ]
