# Generated by Django 4.2.4 on 2023-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimageintro',
            name='bg_image',
            field=models.ImageField(upload_to='media/intro'),
        ),
    ]
