# Generated by Django 4.2.4 on 2023-08-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_rename_image_backgroundimageintro_bg_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimageintro',
            old_name='bg_name',
            new_name='bg_image_name',
        ),
    ]
