# Generated by Django 4.2.4 on 2023-08-27 17:26

from django.db import migrations, models
import intro.validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_rename_bg_name_backgroundimageintro_bg_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimageintro',
            name='bg_image',
            field=models.ImageField(upload_to='media/intro', validators=[intro.validatiors.validate_aspect_ratio_1920_900]),
        ),
    ]
