# Generated by Django 4.2.4 on 2023-09-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_alter_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='image',
            field=models.ManyToManyField(blank=True, to='intro.backgroundimageintro'),
        ),
    ]
